### PR TITLE
Update composer file for laravel 9

### PR DESCRIPTION
**Pull request by remcom**
Updated composer to allow installation for Laravel 9

### CODE REVIEW

**Comment by francescoben** [comment]
Hi, any news on this?

**Comment by grota** [comment]
I had to add this snippet to this MR
```
diff --git a/src/Provider/DbMaintenanceProvider.php b/src/Provider/DbMaintenanceProvider.php
index 74245a4..4aff671 100644
--- a/src/Provider/DbMaintenanceProvider.php
+++ b/src/Provider/DbMaintenanceProvider.php
@@ -46,10 +46,10 @@ class DbMaintenanceProvider extends ServiceProvider

     protected function overrideIlluminateMaintenanceCommands()
     {
-        $this->app->extend('command.up', function ($command, Application $app) {
+        $this->app->extend('Illuminate\\Foundation\\Console\\UpCommand', function ($command, Application $app) {
             return $app->make(UpCommand::class);
         });
-        $this->app->extend('command.down', function ($command, Application $app) {
+        $this->app->extend('Illuminate\\Foundation\\Console\\DownCommand', function ($command, Application $app) {
             return $app->make(DownCommand::class);
         });
```

**Review by grota — CHANGES_REQUESTED** [review]
please add this diff

```
diff --git a/src/Provider/DbMaintenanceProvider.php b/src/Provider/DbMaintenanceProvider.php
index 74245a4..4aff671 100644
--- a/src/Provider/DbMaintenanceProvider.php
+++ b/src/Provider/DbMaintenanceProvider.php
@@ -46,10 +46,10 @@ class DbMaintenanceProvider extends ServiceProvider

     protected function overrideIlluminateMaintenanceCommands()
     {
-        $this->app->extend('command.up', function ($command, Application $app) {
+        $this->app->extend('Illuminate\\Foundation\\Console\\UpCommand', function ($command, Application $app) {
             return $app->make(UpCommand::class);
         });
-        $this->app->extend('command.down', function ($command, Application $app) {
+        $this->app->extend('Illuminate\\Foundation\\Console\\DownCommand', function ($command, Application $app) {
             return $app->make(DownCommand::class);
         });

```

**Comment by wilmardo** [comment]
This would be a good feature to have merged and released, currently it isn't possible to add the package to Laravel 9.

**Comment by damiankloip** [comment]
@RemCom Could you please add the diff above to the PR? This is indeed needed before we can extend this to Laravel 9.

**Comment by remcom** [comment]
@damiankloip I will do that this afternoon and i will let you know

**Comment by damiankloip** [comment]
Thank you @RemCom - I think the above patch should be modified to use `::class` syntax instead.

**Comment by remcom** [comment]
@damiankloip I pushed the changes. Didn't had the time yet to verify it

**Comment by damiankloip** [comment]
Merged and tagged a new release - thanks @RemCom

https://github.com/friendsofcat/laravel-db-maintenance/releases/tag/1.3.0

**Pull request merged**
